### ISSUE TITLE
JS插件--酷炫的打字机效果: Typed.js

### ISSUE THREAD

**Issue by lizheng0515** [lizheng0515/ignore#10]
Type.js是一个轻量级的插件, 用于实现页面文字的打字机效果. 它使用起来非常简单, 只需要几行代码就能实现高大上的打字机效果.

#### 1. 引入Type.js

-   方法1: ES6模块化引入(官方推荐)

```javascript
//npm下载npm install typed.js
```

```javascript
//在js文件中用模块的方式引入import Typed from 'typed.js';
```

采用该方法导入`type.js`需要使用Babel, 否则浏览器不能识别ES6的语法. 如果只是练手, 推荐使用下面的方法.

-   方法2: 常规导入

```javascript
//script标签导入

```

```javascript
//cdn导入  
```

#### 2. 实例化对象

```javascript
  //目标容器 
    var typed = new Typed('.element', {
       strings: ["纠正一个错误的方法有很多", "而解决一个错误的终极方法，就是不给它发生的机会。"], 
       //输入内容, 支持html标签<span class="ag-soft-line-break"></span>   
       typeSpeed: 100, //打字速度<span class="ag-soft-line-break"></span>  
       backSpeed: 50 //回退速度<span class="ag-soft-line-break"></span> 
   });

```

如果想加入鼠标闪烁效果, 引入一下样式

```css
.typed-cursor{     
      opacity: 1;     
      -webkit-animation: blink 0.7s infinite;  
      -moz-animation: blink 0.7s infinite;    
       animation: blink 0.7s infinite; 
}    
@keyframes blink{   
      0% { opacity:1; } 
      50% { opacity:0; }  
     100% { opacity:1; } 
}  
@-webkit-keyframes blink{    
     0% { opacity:1; }     
     50% { opacity:0; }    
     100% { opacity:1; } 
}   
@-moz-keyframes blink{     
   0% { opacity:1; }     
   50% { opacity:0; }      
  100% { opacity:1; }  
}
```

---

1.  Type.js官网: [http://www.mattboldt.com/demos/typed-js/](https://link.jianshu.com?t=http://www.mattboldt.com/demos/typed-js/)
2.  Github文档地址:[https://github.com/mattboldt/typed.js/](https://link.jianshu.com?t=https://github.com/mattboldt/typed.js/)
3.  CDN地址:[http://www.bootcdn.cn/typed.js/](https://link.jianshu.com?t=http://www.bootcdn.cn/typed.js/)
